### ISSUE TITLE
nucleosome profile

### ISSUE THREAD

**Issue by dprat** [uca-mdlab/sanefalcon#12]
In the step for creating the **profiles** we don't get the correct number of files.
In the directory `sanefalcon/training/profiles` we get files for only 1 original bam file by subdirectory.

which means that for subdir **a** we have only 1 file from this subdir, from subdir **b** only 1 file, etc...

and we end up with a `trainNucl.csv` file of 18 lines, when it should be composed by all the files in the training (270 files)

at the moment in the directory `sanefalcon/training/profiles` we have :
18 * 22 * 4 = 1584 files:
- 18 files (each of them coming from a uniq subdir)
- 22 chr
- 4 = '.rev', '.irev', '.fwd', '.ifwd'

but we should have : 
270 * 22 * 4 = 19440 files

**Comment by marcomilanesio** [comment]
using `b92e4b5fab6b041c4d224d82831ffad74bfa1b68`, what's the result of `nucleosome.tracker.py` ?

**Comment by marcomilanesio** [comment]
Also, send me last part of the log file

**Comment by dprat** [comment]
if i use nucleosome/tracker.py it doesn't work.
it can't find package `nucleosome`and `multi`
I launched it from sanefalcon directory:

`python nucleosome/tracker.py`

> Traceback (most recent call last):
  File "nucleosome/tracker.py", line 5, in <module>
    import nucleosome.nucleosome_detector as nd
ModuleNotFoundError: No module named 'nucleosome'

I've been missing something from the documentation about this module import...

and when i launch:
`python main.py -t`

i obtain this error now : 
>Traceback (most recent call last):
  File "main.py", line 32, in <module>
    nucleosome_file = monitor.training(config)
  File "/home/mdlab/sanefalcon/monitor.py", line 110, in training
    mapping, merged, anti = prepare_and_merge(f, rs, config)
  File "/home/mdlab/sanefalcon/monitor.py", line 85, in prepare_and_merge
    batches = fm.prepare_train_folder(bamlist, batchsize)
  File "/home/mdlab/sanefalcon/manager/file_manager.py", line 50, in prepare_train_folder
    batch_dir = os.path.join(self.trainfolder, letters[num_batch])
IndexError: list index out of range

**Comment by marcomilanesio** [comment]
if you call it like that remove `'../'` from `'../sanefalcon.conf'`.
In any case, give me `runs[0]`

**Comment by dprat** [comment]
If i launched it from the terminal this way:
`python -m nucleosome.tracker`
It print me this for `runs[0]`

>('4', '/home/mdlab/storage/sanefalcon/training/a/anti.4', '/home/mdlab/storage/sanefalcon/training/a/nucl_track_anti.4')

**Comment by marcomilanesio** [comment]
Closed [15e8d77](https://github.com/uca-mdlab/sanefalcon/commit/15e8d7725e51c7e09e3b16f767baeae3611b3b1d)
