### ISSUE TITLE
number of samples in nucleosome profile doesn't match number of samples in the training

### ISSUE THREAD

**Issue by dprat** [uca-mdlab/sanefalcon#13]
1) For the `list_testing1` in the training directory we have 304 samples (**.bam** files) but in `training/profiles` we have only 275 uniq samples which are all in the `trainingNucleosome.csv` file. But we expect 304 uniq files in order to get 304 nucleosome (the same amount than in the training).

2) the `trainingNucleosome.csv` and the `testingNucleosome.csv` are the same files.
The `testingNucleosome.csv` is supposed to correspond to the nucleosome profiles of testing samples, so for the `list_testing1` we should get a file composed of **72 lines**, since we have 72 samples in this testing

**Comment by marcomilanesio** [comment]
Related to [#4](https://github.com/uca-mdlab/sanefalcon/issues/4).

```
$ wc -l  /home/mdlab/storage/data_nice/seqff_reference_sanefalcon.csv
377 /home/mdlab/storage/data_nice/seqff_reference_sanefalcon.csv
```

We have to remove 2 samples:

```
$ grep -e "p2_096" -e "p42_089" /home/mdlab/storage/data_nice/seqff_reference_sanefalcon.csv
p2_096_dedup.bam        20.1075 Female
```
376 samples total. 72 testing and 304 training.
From the logs:
```
2020-01-10 15:32:18,182 - __main__              - DEBUG   : Testing set for list_testing1: 72 samples
2020-01-10 15:32:18,182 - __main__              - DEBUG   : Training set for list_testing1: 304 samples
```
And at the end, ff is calculated for 72 samples:
```
$ grep 'ff(' sanefalcon.log | wc -l
72
```
**BUT:**

- Only 275 made through nucleosome profiles. Upstream and downstreams don't match. We have **NO** sample for which `22 * 4` files have been computed (in `/training/profiles`). I guess multiprocessing fails somewhere without informing
- When running the model, only **male** samples are considered. For this subset, 
```
125 samples overlap
46 samples noOverlap
```
Only 125 samples are used in the training of the linear model.

Suggestions?

**Comment by dprat** [comment]
Yes removing the 2 samples from the **training** is correct.
and calculating the ff for 72 samples is also correct.
But in the training we are supposed to get `22*4` files for each sample in the training, so by example fort `list_testin1` we should obtain `22*4*304` files (*.rev, *.fwd, *.irev, *.ifwd) and end up with a `trainingNucleosome.csv` file of **304** lines and a `testingNucleosome.csv` file of **72** lines. I just check and we have a random number for all the data.

Concerning the **male** samples, you're right. Since we use **seqff** data as reference we are supposed to use both **male** and **female** data. So we need to modify this to take into account also the **female** sample.

But I don't understand why we have :
```
125 samples overlap
46 samples noOverlap
```
does those 125 samples corresponds to the **male** ? 

In this first training we are supposed to have 142 male
```
cat list_testing[2-5].txt | cut -d ';' -f3 | sort | uniq -c
    162 F
    142 M
```

So does this : 
```
125 samples overlap
46 samples noOverlap
```
comes from the overlap between the samples in the **training** and in the **reference file** (= file with seqff values) without checking the gender ?
If so, then there's a mistake somewhere.

What I was expecting was to get at least `142 males` samples (since it's selecting only male samples).
But now if we modify it to take into account also the **female** samples then we should get the **304** samples

**Comment by marcomilanesio** [comment]
1. is solved.
2. still on going

**Comment by marcomilanesio** [comment]
reopening on 2.
