### ISSUE TITLE
Remaining steps

### ISSUE THREAD

**Issue by marcomilanesio** [uca-mdlab/sanefalcon#4]
Figure out data pipeline for the remaining steps (validation/ff calcul/etc)

**Comment by marcomilanesio** [comment]
From the documentation of Sanefalcon:

> reverse the upstream profile (left most value must become rightmost etc), then stitch the two together by putting the downstream profiles after the upstream profiles.

So it seems to me that **for each chromosome**:

- `profilefolder/*.fwd` and `profilefolder/*.rev` are used to create the upstream profiles
- `profilefolder/*.ifwd` and `profilefolder/*.irev` are used to create the downstream profiles
- upstream profile has to be reversed
- downstream profile has to be appended.

So, suppose a case with 1 manip (e.g., `p0.bam`), with the following streams (i.e., "sum" of profile files):
```
upstream = {'chr1': 1, 'chr2': 2, 'chr3': 2}
downstream = {'chr1': 1, 'chr2': 4, 'chr3': 3}
```
From the documentation:

> Note there is a value in the middle that has to be removed as both sides also take the nucleosome center base pair into account, thus providing this number twice. You should find the last number from the upstream matches the first number of the downstream profiles when putting them together.

So, given all that, the resulting line would be:
```
p0.bam, 2, 2, 1, 4, 3
```

Right? 
What is the `nucleosome center base pair`?

**Comment by dprat** [comment]
yes it's correct.

Concerning the nucleosome center base pair, from what I understand, I guess he's talking about base pair : A-T, C-G ...
So we just need to know that we have to take off one value at end of the upstream file (once it's reversed) or at the start or the downstream file

**Comment by marcomilanesio** [comment]
This does not happens in the test files I'm using. `upstream.reverse()[-1] <> downstream[0]`

For example:
```
2019-07-15 14:59:40,714 - DEBUG: Stream up (reversed): p10_065_dedup.bam. length 22. pos[0]: 11351.0, pos[-1]: 70600.0
2019-07-15 14:59:40,731 - DEBUG: Stream down: p10_065_dedup.bam. length 22. pos[0]: 68426.0, pos[-1]: 10821.0
```
From what I understood there should be 2 equal numbers there. Which are not.
Namely: `70600 <> 68426`
Any clue on what to look for for an error?

**Comment by marcomilanesio** [comment]
> yes it's correct.
> 
> Concerning the nucleosome center base pair, from what I understand, I guess he's talking about base pair : A-T, C-G ...
> So we just need to know that we have to take off one value at end of the upstream file (once it's reversed) or at the start or the downstream file

Not sure why you say "So".
Also, we never considered base pairs in the code. Where shoud it be referenced?

**Comment by dprat** [comment]
From what I understand, a base pair correspond to a read start position. Nothing more.

From the code : 

```
echo $SIMPLE,\`LC_NUMERIC=C awk -F"," '{ for(i=1;i<=NF;i++){ fetal[i]+=$i } } END { for(i=1;i<=NF;i++) {printf "%s,",fetal[i]}; print "";}' \
		${SAMPLE//.1.rev.np/}.*.rev.np ${SAMPLE//.1.rev.np/}.*.fwd.np\`
```


Here I made a mistake, we actually calculate the sum of each col for all the files
To be clear : 
- The input correspond to all the file *.fwd and *.rev (each file is one line with 146 values = 146 col)
- The output correspond to one file, where each row correspond to 1 sample, and each is composed by 146 col.

So by example we have : 

- sample.1.chr1.fwd : 200, 300, ..., 150
- sample.1.chr2.fwd : 300, 200, ..., 130
- sample.1.chr1.rev : 200, 100, ..., 100
- sample1.chr2.rev : 300, 150, ..., 150

output -> :
- sample.1 :  1000, 750, ..., 530

Then you do the same for the *.ifwd and *.irev files

**Comment by marcomilanesio** [comment]
Running with small cohorte fails model running.
In training phase (2 samples):
```
2 samples overlap
0 samples noOverlap
/usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:3049: RuntimeWarning: invalid value encountered in double_scalars
  0.5*df, 0.5, np.fmin(np.asarray(df / (df + t_squared)), 1.0)
Train polyfit: Pearson: (1.0, 0.0)
Train polyfit: errorRate: 2.6645352591003757e-15
Train linearModel: Pearson: (1.0, 0.0)
Train linearModel: Residual sum of squares: 0.00
Train linearModel: Variance score: 1.00
Train linearModel: errorRate: 1.9539925233402755e-14
124.32541608757926 5.567035768027761
```

Meaning that the training is properly conducted and a model is created.
When testing:
```
0 samples overlap
1 samples noOverlap
/usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:3033: RuntimeWarning: Mean of empty slice.
  mx = x.mean()
/usr/local/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:3034: RuntimeWarning: Mean of empty slice.
  my = y.mean()
/usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:3038: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den
Test polyfit: Pearson: (nan, nan)
/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
Test polyfit: errorRate: nan
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    predictor.run_model(training_nucleosome_file, training_reference_file, outmodel_file, nucleosome_file, reference_file)
  File "/home/marco/sw/github/mdlab/sanefalcon/predictor.py", line 383, in run_model
    te_linearmodel = test_linear_model(new_selected_regions, new_yVals, linear_model, "Test")
  File "/home/marco/sw/github/mdlab/sanefalcon/predictor.py", line 171, in test_linear_model
    predicted = clf.predict(samples)
  File "/usr/local/lib/python3.6/site-packages/sklearn/linear_model/base.py", line 221, in predict
    return self._decision_function(X)
  File "/usr/local/lib/python3.6/site-packages/sklearn/linear_model/base.py", line 204, in _decision_function
    X = check_array(X, accept_sparse=['csr', 'csc', 'coo'])
  File "/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 521, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```
Looks like it needs more samples in the testing phase.
@dprat can you check with a small cohorte? (use 94f827b20df8e5bbfddf303e7b37d43413d9bff5)

**Comment by marcomilanesio** [comment]
Relaunching. Any news on this?

**Comment by dprat** [comment]
-  for the first problem:

> Running with small cohorte fails model running.
> In training phase (2 samples):
> 
> ```
> 2 samples overlap
> 0 samples noOverlap
> /usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:3049: RuntimeWarning: invalid value encountered in double_scalars
>   0.5*df, 0.5, np.fmin(np.asarray(df / (df + t_squared)), 1.0)
> Train polyfit: Pearson: (1.0, 0.0)
> Train polyfit: errorRate: 2.6645352591003757e-15
> Train linearModel: Pearson: (1.0, 0.0)
> Train linearModel: Residual sum of squares: 0.00
> Train linearModel: Variance score: 1.00
> Train linearModel: errorRate: 1.9539925233402755e-14
> 124.32541608757926 5.567035768027761
> ``` 

I've tried with more samples and for me it's working, so i for me it was just a problem coming from the number of samples which was too low.

- for the 2nd problem:

> Meaning that the training is properly conducted and a model is created.
> When testing:
> 
> ```
> 0 samples overlap
> 1 samples noOverlap
> /usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:3033: RuntimeWarning: Mean of empty slice.
>   mx = x.mean()
> /usr/local/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> /usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:3034: RuntimeWarning: Mean of empty slice.
>   my = y.mean()
> /usr/local/lib/python3.6/site-packages/scipy/stats/stats.py:3038: RuntimeWarning: invalid value encountered in double_scalars
>   r = r_num / r_den
> Test polyfit: Pearson: (nan, nan)
> /usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
>   out=out, **kwargs)
> Test polyfit: errorRate: nan
> Traceback (most recent call last):
>   File "main.py", line 42, in <module>
>     predictor.run_model(training_nucleosome_file, training_reference_file, outmodel_file, nucleosome_file, reference_file)
>   File "/home/marco/sw/github/mdlab/sanefalcon/predictor.py", line 383, in run_model
>     te_linearmodel = test_linear_model(new_selected_regions, new_yVals, linear_model, "Test")
>   File "/home/marco/sw/github/mdlab/sanefalcon/predictor.py", line 171, in test_linear_model
>     predicted = clf.predict(samples)
>   File "/usr/local/lib/python3.6/site-packages/sklearn/linear_model/base.py", line 221, in predict
>     return self._decision_function(X)
>   File "/usr/local/lib/python3.6/site-packages/sklearn/linear_model/base.py", line 204, in _decision_function
>     X = check_array(X, accept_sparse=['csr', 'csc', 'coo'])
>   File "/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 521, in check_array
>     "if it contains a single sample.".format(array))
> ValueError: Expected 2D array, got 1D array instead:
> array=[].
> Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
> ```
> 
> Looks like it needs more samples in the testing phase.
> @dprat can you check with a small cohorte? (use [94f827b](https://github.com/uca-mdlab/sanefalcon/commit/94f827b20df8e5bbfddf303e7b37d43413d9bff5))

I think that here the problem is coming from :

> 0 samples overlap
> 1 samples noOverlap

which mean that files in trainRef.csv and the one in trainNucl.csv do not match because it doesn't find the correct name.

in the trainRef.csv the name has to be the exact same has in the start of each line of trainNucl.csv, otherwise it will not match.

**Comment by marcomilanesio** [comment]
Closing. Move discussion to #14
